#@ load("@ytt:data", "data")
---
kind: Service
apiVersion: v1
metadata:
  name: dexsvc
  namespace: tanzu-system-auth
  labels:
    app: dex
spec:
  type: #@ data.values.dex_service_type
  ports:
    - name: "dex"
      protocol: TCP
      port: 5556
      targetPort: "https"
      nodePort: 30167
  selector:
    app: dex
