#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: gangway
  namespace: tanzu-system-auth
type: Opaque
data:
  # openssl rand -base64 32 | pbcopy
  sesssionKey: #@ data.values.gangway_session_key_base64
  # clientSecret=$(openssl rand -base64 32)
  # echo -n "$clientSecret" | base64
  clientSecret: #@ base64.encode(data.values.gangway_client_secret)
